### ISSUE TITLE
aa

### ISSUE THREAD

**Issue by mikowaru** [mikowaru/strony#2]
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Szkoła Średnia</title>
</head>
<body>

    <header>
        <div class="top-left">
            <h1>Szkoła Średnia</h1>
        </div>
        <div class="top-center">
            <nav>
                <ul>
                    <li><a href="#home">Home</a></li>
                    <li><a href="#szkola">Szkoła</a></li>
                    <li><a href="#rozne">Różności</a></li>
                    <li><a href="#rodo">RODO</a></li>
                    <li><a href="#erasmus">Erasmus+</a></li>
                    <li><a href="#poczta">Poczta</a></li>
                    <li><a href="#plan">Plan Nauczycieli</a></li>
                    <li><a href="#dziennik">Dziennik</a></li>
                    <li><a href="#galeria">Galeria</a></li>
                </ul>
            </nav>
        </div>
        
    </header>

    <main>
        <div class="left">
            
        </div>
        
        <div class="center">
            
        </div>

        <div class="right">
            
        </div>
    </main>

    <footer>
        <p>&copy; 2023 Szkoła Średnia. Wszelkie prawa zastrzeżone.</p>
    </footer>

</body>
</html>

body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

header {
    background-color: #333;
    color: #fff;
    padding: 10px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.top-center {
    text-align: center;
}

nav {
    margin-top: 10px;
}

ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    background-color: #444;
    overflow: hidden;
}

li {
    float: left;
}

a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

a:hover {
    background-color: #555;
}

main {
    display: flex;
}

.left, .center, .right {
    flex: 1;
    padding: 20px;
}

footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px;
    position: fixed;
    bottom: 0;
    width: 100%;
}

**Comment by mikowaru** [comment]
"<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Szkoła Średnia</title>
</head>
<body>

    <header>
        <div class="top-left">
            <h1>Szkoła Średnia</h1>
        </div>
        <div class="top-center">
            <nav>
                <ul>
                    <li><a href="#home">Home</a></li>
                    <li><a href="#szkola">Szkoła</a></li>
                    <li><a href="#rozne">Różności</a></li>
                    <li><a href="#rodo">RODO</a></li>
                    <li><a href="#erasmus">Erasmus+</a></li>
                    <li><a href="#poczta">Poczta</a></li>
                    <li><a href="#plan">Plan Nauczycieli</a></li>
                    <li><a href="#dziennik">Dziennik</a></li>
                    <li><a href="#galeria">Galeria</a></li>
                </ul>
            </nav>
        </div>
        
    </header>

    <main>
        <div class="left">
            
        </div>
        
        <div class="center">
            
        </div>

        <div class="right">
            
        </div>
    </main>

    <footer>
        <p>&copy; 2023 Szkoła Średnia. Wszelkie prawa zastrzeżone.</p>
    </footer>

</body>
</html>

**Comment by mikowaru** [comment]
class="dropdown">
                        <a href="#szkola">Szkoła</a>
                        <div class="dropdown-content">
                            <a href="#">Podzakładka 1</a>
                            <a href="#">Podzakładka 2</a>
                            <a href="#">Podzakładka 3</a>
                            <a href="#">Podzakładka 4</a>
                            <a href="#">Podzakładka 5</a>
                        </div>

.dropdown {
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #444;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    z-index: 1;
}

.dropdown:hover .dropdown-content {
    display: block;

**Comment by mikowaru** [comment]
Tak, możesz stworzyć prosty pokaz zdjęć za pomocą HTML i CSS, ale do bardziej zaawansowanych funkcji, takich jak automatyczna zmiana slajdów czy obsługa gestów, będziesz potrzebować również JavaScript. Oto przykładowa struktura dla prostego pokazu zdjęć:

HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <title>Simple Image Slider</title>
</head>
<body>

<div class="slider-container">
  <div class="slide">
    <img src="image1.jpg" alt="Slide 1">
  </div>
  <div class="slide">
    <img src="image2.jpg" alt="Slide 2">
  </div>
  <div class="slide">
    <img src="image3.jpg" alt="Slide 3">
  </div>
</div>

</body>
</html>
```

CSS (styles.css):
```css
body {
  margin: 0;
  font-family: Arial, sans-serif;
}

.slider-container {
  width: 100%;
  overflow: hidden;
}

.slide {
  display: none;
}

img {
  width: 100%;
  height: auto;
}

/* Dodatkowy styl do kontroli przycisków nawigacyjnych (jeśli potrzebujesz) */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

.prev:hover, .next:hover {
  background-color: rgba(0, 0, 0, 0.8);
}
```

Ten przykład zawiera prosty kontener dla slajdów (`slider-container`) i ukrywa slajdy za pomocą `display: none`. Możesz dostosować ten kod zależnie od swoich potrzeb i stylów. Jeśli chcesz, aby slajdy zmieniały się automatycznie, bądź użyj JavaScript, bądź skorzystaj z gotowych bibliotek do obsługi karuzeli obrazków.
